# ALL ABOUT NUMPY

In [1]:
import numpy as np   ##numpy is used for numerical operation in terms of matrix and array

In [3]:
##Upcasting process:
np.array([1, 2, 3.0])

array([1., 2., 3.])

In [4]:
#two dimensions:
np.array([[1, 2], [3, 4]])
 


array([[1, 2],
       [3, 4]])

In [5]:
type( np.array([[1, 2], [3, 4]]))

numpy.ndarray

In [6]:
np.array([1, 2, 3], ndmin=5)   ##ndmin parameter help to controlling the dimesnsions of array

array([[[[[1, 2, 3]]]]])

In [7]:
type(np.array([1, 2, 3], ndmin=5))

numpy.ndarray

In [8]:
 np.array([1, 2, 3], dtype=complex)   ##dtype parameter controlling datatype of element belonging to array

array([1.+0.j, 2.+0.j, 3.+0.j])

In [9]:
x = np.array([(1,2),(3,4)],dtype=[('a','<i2'),('b','<i8')]) ##define datatype of particular element of array
x                                                           ## i2 means 16 bit,i4 means 32 bit and i8 means 64 bit

array([(1, 2), (3, 4)], dtype=[('a', '<i2'), ('b', '<i8')])

In [13]:
x[1][1]

4

In [12]:
type(x[1][1])

numpy.int64

In [14]:
##Creating an array from sub-classes:
np.mat(np.array([[1, 2],[4,7]]))

matrix([[1, 2],
        [4, 7]])

In [16]:
np.mat('1 2; 3 4')  ##Matrix is an instance of an array

matrix([[1, 2],
        [3, 4]])

In [17]:
#Convert the input to an array.
a = [1, 2]
type(a)

list

In [18]:
np.asarray(a)   ##asarray() function performs same as array() function

array([1, 2])

In [20]:
np.array(a)

array([1, 2])

In [19]:
type(np.asarray(a))

numpy.ndarray

In [21]:
type(np.array(a))

numpy.ndarray

In [25]:
a = np.array(np.asarray([1,2]), dtype=np.float32)  ##upcastig thing operation 
a

array([1., 2.], dtype=float32)

In [23]:
np.asarray([1,2]) is a

False

In [27]:
np.asarray([1,2], dtype=np.float64) is a  ##Return false bcz datatype of element are not same

False

In [28]:
issubclass(np.matrix, np.ndarray)  #method chechk the instances

True

In [31]:
type(np.matrix([[1, 2]]))

numpy.matrix

In [40]:
s = np.matrix([[1, 2]])
np.asanyarray(s) ##Converted in any array but here asanyarray() function do nothing bcz we no that matrix is an instance of array

matrix([[1, 2]])

In [38]:
np.asarray(s) is s

False

In [42]:
np.asanyarray(s) is s

True

In [43]:
type(np.asarray(s))

numpy.ndarray

In [44]:
type(np.asanyarray(s))

numpy.matrix

In [46]:
a = [1, 2] 
np.asanyarray(a)  ##CXonverted in any array

array([1, 2])

In [48]:
x = np.array([1, 2, 3])
x

array([1, 2, 3])

In [49]:
y = x  ##solo copy:- share same memory location in heap

In [55]:
z = np.copy(x)  ##deep copy:- acquire separate space in the heap

In [58]:
y[0] = 100
y

array([100,   2,   3])

In [59]:
x   ##The value of x and y are same bcz of solo copy

array([100,   2,   3])

In [52]:
id(x[0])

2028793827376

In [53]:
id(y[0])

2028793827408

In [56]:
id(z[0])

2028775968368

In [60]:
#Construct an array by executing a function over each coordinate(rows and column).
np.fromfunction(lambda i, j: i == j, (3, 3), dtype=int)  ##fromfunction() is used to construct an array

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

In [61]:
np.fromfunction(lambda i, j: i * j, (3, 3), dtype=int)

array([[0, 0, 0],
       [0, 1, 2],
       [0, 2, 4]])

In [65]:
iterable = (x*x for x in range(5))  ##tuple kind of things gives generator object
                                    ##list kind of things gives data in list
iterable

<generator object <genexpr> at 0x000001D85D8978C8>

In [66]:
iterable = [x*x for x in range(5)]  ##tuple kind of things gives generator object
                                    ##list kind of things gives data in list
iterable

[0, 1, 4, 9, 16]

In [67]:
np.fromiter(iterable, float) ##Perform same operation like iter() during dealing with iterator
                             ##Along with upcasting feature

array([ 0.,  1.,  4.,  9., 16.])

In [68]:
a = np.fromstring('234 234',sep=' ')  ##Happen only on integer data not a string data
a

array([234., 234.])

In [69]:
a = np.fromstring('1,2',sep=',')  ## happen only integer data not string data
a

array([1., 2.])

In [72]:
x1=np.array([1,2,3,4])
x2=np.array(['a','dd','xyz','12'])
x3=np.array([1.1,2,3,4])
x4=np.array([1.1,2,3,4])

In [73]:
rec = np.core.records.fromarrays([x1,x2,x3,x4],names='a,b,c,d')  # How to create record array from a list of arrays
re

rec.array([(1, 'a', 1.1, 1.1), (2, 'dd', 2. , 2. ), (3, 'xyz', 3. , 3. ),
           (4, '12', 4. , 4. )],
          dtype=[('a', '<i4'), ('b', '<U3'), ('c', '<f8'), ('d', '<f8')])

In [74]:
print(rec[1]["a"])

2


In [75]:
print(rec[1]["a"])

2


In [76]:
my_list = [1,2,3]
import numpy as np
arr = np.array(my_list)
print("Type/Class of this object:",type(arr))
print("Here is the vector\n--------------------\n",arr)

Type/Class of this object: <class 'numpy.ndarray'>
Here is the vector
--------------------
 [1 2 3]


In [77]:
my_mat = [[1,2,3],[4,5,6],[7,8,9]]
mat = np.array(my_mat)
print("Type/Class of this object:",type(mat))
print("Here is the matrix\n----------\n",mat,"\n----------")
print("Dimension of this matrix: ",mat.ndim,sep='')   #ndim gives the dimensison, 2 for a matrix, 1 for a vector
print("Size of this matrix: ", mat.size,sep='')       #size gives the total number of elements
print("Shape of this matrix: ", mat.shape,sep='')     #shape gives the number of elements along each axes (dimension)
print("Data type of this matrix: ", mat.dtype,sep='') #dtype gives the data type contained in the array


Type/Class of this object: <class 'numpy.ndarray'>
Here is the matrix
----------
 [[1 2 3]
 [4 5 6]
 [7 8 9]] 
----------
Dimension of this matrix: 2
Size of this matrix: 9
Shape of this matrix: (3, 3)
Data type of this matrix: int32


In [78]:
my_mat = [[1.1,2,3],[4,5.2,6],[7,8.3,9]]
mat = np.array(my_mat)
print("Data type of the modified matrix: ", mat.dtype,sep='') #dtype gives the data type contained in the array
print("\n\nEven tuples can be converted to ndarrays...")


Data type of the modified matrix: float64


Even tuples can be converted to ndarrays...


In [79]:
b = np.array([(1.5,2,3), (4,5,6)])
print("We write b = np.array([(1.5,2,3), (4,5,6)])")
print("Matrix made from tuples, not lists\n---------------------------------------")
print(b)

We write b = np.array([(1.5,2,3), (4,5,6)])
Matrix made from tuples, not lists
---------------------------------------
[[1.5 2.  3. ]
 [4.  5.  6. ]]


In [80]:
list(range(5,16,2))

[5, 7, 9, 11, 13, 15]

In [81]:
list(range(50,-1,5))

[]

In [82]:
list(range(50,-1,-5))

[50, 45, 40, 35, 30, 25, 20, 15, 10, 5, 0]

In [84]:
np.arange(0,11,2.5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [4]:
import numpy as np
print((np.linspace(1,5,50)))

[1.         1.08163265 1.16326531 1.24489796 1.32653061 1.40816327
 1.48979592 1.57142857 1.65306122 1.73469388 1.81632653 1.89795918
 1.97959184 2.06122449 2.14285714 2.2244898  2.30612245 2.3877551
 2.46938776 2.55102041 2.63265306 2.71428571 2.79591837 2.87755102
 2.95918367 3.04081633 3.12244898 3.20408163 3.28571429 3.36734694
 3.44897959 3.53061224 3.6122449  3.69387755 3.7755102  3.85714286
 3.93877551 4.02040816 4.10204082 4.18367347 4.26530612 4.34693878
 4.42857143 4.51020408 4.59183673 4.67346939 4.75510204 4.83673469
 4.91836735 5.        ]


In [5]:
np.linspace(2.0, 3.0, num=5)

array([2.  , 2.25, 2.5 , 2.75, 3.  ])

In [7]:
np.linspace(2.0, 3.0, num=5, endpoint=False)  ##Here endpoint in defind range are not considered

array([2. , 2.2, 2.4, 2.6, 2.8])

In [8]:
np.linspace(2.0, 3.0, num=9, retstep=True)   ##retstep parameter gives differences between 2 value

(array([2.   , 2.125, 2.25 , 2.375, 2.5  , 2.625, 2.75 , 2.875, 3.   ]), 0.125)

In [93]:
A = np.linspace(0,12*np.pi,1001)
A

array([ 0.        ,  0.03769911,  0.07539822, ..., 37.62371362,
       37.66141273, 37.69911184])

In [10]:
np.logspace(2.0, 3.0, num=9,base = 10)  ##logspace() fun gives log value to the base 10 of each element of array

array([ 100.        ,  133.35214322,  177.827941  ,  237.13737057,
        316.22776602,  421.69650343,  562.34132519,  749.89420933,
       1000.        ])

In [12]:
np.logspace(2.0, 3.0, num=9,base = 10, endpoint= False)

array([100.        , 129.1549665 , 166.81005372, 215.443469  ,
       278.25594022, 359.38136638, 464.15888336, 599.48425032,
       774.26368268])

In [13]:
np.logspace(2.0, 3.0, num=4, base=2.0)

array([4.        , 5.0396842 , 6.34960421, 8.        ])

In [15]:
#Construct a diagonal array.
x = np.arange(16).reshape((4,4))
x

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [18]:
np.arange(16).reshape((-1,4))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [19]:
np.arange(16).reshape((4,-1))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [20]:
np.diag(x)

array([ 0,  5, 10, 15])

In [21]:
np.diag(x, k=2) ## hide column before the k=2 column along with their connected row, hiding start from starting column

array([2, 7])

In [23]:
np.diag(x, k=-1)   ## hide column before the k= 1 column along with their connected row hiding start from last column

array([ 4,  9, 14])

In [24]:
np.diag(np.diag(x)) ##constructing diagonal array using diagonal element

array([[ 0,  0,  0,  0],
       [ 0,  5,  0,  0],
       [ 0,  0, 10,  0],
       [ 0,  0,  0, 15]])

In [31]:
np.diagflat([[1,2]])

array([[1, 0],
       [0, 2]])

In [35]:
np.diagflat([[1,2],[3,4]], k=1)

array([[0, 1, 0, 0, 0],
       [0, 0, 2, 0, 0],
       [0, 0, 0, 3, 0],
       [0, 0, 0, 0, 4],
       [0, 0, 0, 0, 0]])

In [26]:
np.diagflat([1,2], k=1)

array([[0, 1, 0],
       [0, 0, 2],
       [0, 0, 0]])

In [87]:
##Vector creation
print("Vector of zeroes\n---------------------")
print(np.zeros(5))

Vector of zeroes
---------------------
[0. 0. 0. 0. 0.]


In [88]:
##Matrix creation
print("Matrix of zeroes\n--------------------")
print(np.zeros((3,4)))     ##Notice Tuples

Matrix of zeroes
--------------------
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [89]:
print("Vector of ones\n---------------------")
print(np.ones(5))

Vector of ones
---------------------
[1. 1. 1. 1. 1.]


In [91]:
print("Matrix of ones\n---------------------")
print(np.ones((5,3)))

Matrix of ones
---------------------
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [92]:
print("Matrix of ones\n---------------------")
print(np.ones((5,2,8)))        ##Note matrix dimension specified by Tuples

Matrix of ones
---------------------
[[[1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1.]]]


In [93]:
print("Matrix of 5's\n---------------------")
print(5+np.ones((3,5)))

Matrix of 5's
---------------------
[[6. 6. 6. 6. 6.]
 [6. 6. 6. 6. 6.]
 [6. 6. 6. 6. 6.]]


In [94]:
print("Empty matrix\n-------------\n", np.empty((3,5)))  ##empty() gives any random element of matxix

Empty matrix
-------------
 [[6. 6. 6. 6. 6.]
 [6. 6. 6. 6. 6.]
 [6. 6. 6. 6. 6.]]


In [95]:
mat1 = np.eye(4)        ##eye() function is used to create identity matrix
print("Identity matrix of dimension", mat1.shape)
print(mat1)

Identity matrix of dimension (4, 4)
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [36]:
print("Random number generation (from Uniform distribution)")
print(np.random.rand(2,3)) ##E2 by 3 matrix with random numbers ranging from 0 to 1, Note no Tuple is necessary 
                           ## rand() always gives uniform distribution value.

Random number generation (from Uniform distribution)
[[0.68257256 0.04896317 0.44700616]
 [0.35721047 0.29158269 0.92537567]]


In [37]:
print("Numbers from Normal distribution with zero mean and standard deviation 1 i.e. standard normal")
print(np.random.randn(4,3))

Numbers from Normal distribution with zero mean and standard deviation 1 i.e. standard normal
[[-0.00684879  0.31711344 -1.76469774]
 [ 1.01459474 -1.86730481  1.82036125]
 [ 0.18904047  0.27352023 -1.0051638 ]
 [-0.26068416  1.12688449  1.55750832]]


In [40]:
print("Random integer vector:",np.random.randint(1,10)) ##randint (low, high, # of samples to be drawn)
print ("\nRandom integer matrix")                       ##any random value returns between 1 to 10


Random integer vector: 7

Random integer matrix


In [41]:
print(np.random.randint(1,100,(4,4)))               ##randint (low, high, # of samples to be drawn in a tuple to form a matrix)
print("\n20 samples drawn from a dice throw:",np.random.randint(1,7,20)) # 20 samples drawn from a dice throw

[[42 30 71 68]
 [83 32 93 95]
 [92 73 32 19]
 [93 25 76 58]]

20 samples drawn from a dice throw: [5 6 5 6 5 5 2 6 2 3 3 6 4 5 1 3 5 2 4 5]


In [43]:
from numpy.random import randint as ri
A = ri(1,100,10) # Vector of random interegrs
print("\nVector of random integers\n",'-'*50,"\n",A)
print("\nHere is the sorted vector\n",'-'*50,"\n",np.sort(A))



Vector of random integers
 -------------------------------------------------- 
 [64 80 59 13 18 60 29  5 48 47]

Here is the sorted vector
 -------------------------------------------------- 
 [ 5 13 18 29 47 48 59 60 64 80]


In [47]:
M = ri(1,100,25).reshape(5,5) ##Matrix of random interegrs
print("\nHere is the sorted matrix along each column\n",'-'*50,"\n",np.sort(M, axis=1, kind='mergesort'))
M


Here is the sorted matrix along each column
 -------------------------------------------------- 
 [[ 3 21 54 72 75]
 [27 35 53 60 87]
 [ 8 12 19 72 96]
 [21 27 36 66 91]
 [22 51 62 68 89]]


array([[72, 75,  3, 54, 21],
       [53, 27, 60, 35, 87],
       [12, 19,  8, 72, 96],
       [91, 27, 66, 36, 21],
       [22, 89, 62, 68, 51]])

In [48]:
print("Max of M:", M.max())

Max of M: 96


In [50]:
print("Max of a location:", M.argmax(axis= 1))  ##argmax() returns the location where the maximum element of the array present at specified index


Max of a location: [1 4 4 0 1]


In [52]:
##Indexing and Slicing
arr = np.arange(0,11)
print("Array:",arr)


Array: [ 0  1  2  3  4  5  6  7  8  9 10]


In [53]:
print("Element at 7th index is:", arr[7])


Element at 7th index is: 7


In [54]:
print("Elements from 3rd to 5th index are:", arr[3:6:2])


Elements from 3rd to 5th index are: [3 5]


In [55]:
print("Elements up to 4th index are:", arr[:4])
arr

Elements up to 4th index are: [0 1 2 3]


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [56]:
print("Elements from last backwards are:", arr[-1:7:-1])


Elements from last backwards are: [10  9  8]


In [57]:
print("Elements at 2nd, 4th, and 9th index are:", arr[[2,4,9]]) # Pass a list as a index to subset

Elements at 2nd, 4th, and 9th index are: [2 4 9]


In [60]:
import numpy as np 
mat = np.array(ri(10,100,15)).reshape(3,5)
print("Matrix of random 2-digit numbers\n--------------------------------\n",mat)
#print(mat[1:4,3:5])
mat[0:3,[1,3]]

Matrix of random 2-digit numbers
--------------------------------
 [[13 39 68 27 58]
 [76 46 68 37 16]
 [73 82 47 28 28]]


array([[39, 27],
       [46, 37],
       [82, 28]])

In [61]:
print("\nDouble bracket indexing\n------------------------")
print("Element in row index 1 and column index 2:", mat[1][1])
mat


Double bracket indexing
------------------------
Element in row index 1 and column index 2: 46


array([[13, 39, 68, 27, 58],
       [76, 46, 68, 37, 16],
       [73, 82, 47, 28, 28]])

In [62]:
print("\nSingle bracket with comma indexing\n----------------------------------")
print("Element in row index 1 and column index 2:", mat[1,2])
print("\nRow or column extract\n----------------------")



Single bracket with comma indexing
----------------------------------
Element in row index 1 and column index 2: 68

Row or column extract
----------------------


In [63]:
print("Entire row at index 2:", mat[2])
print("Entire column at index 3:", mat[:,3])

Entire row at index 2: [73 82 47 28 28]
Entire column at index 3: [27 37 28]


In [64]:
print("\nSubsetting sub-matrices\n--------------------------")
print("Matrix with row indices 1 and 2 and column indices 3 and 4\n", mat[1:3,3:5])


Subsetting sub-matrices
--------------------------
Matrix with row indices 1 and 2 and column indices 3 and 4
 [[37 16]
 [28 28]]


In [65]:
print("Matrix with row indices 0 and 1 and column indices 1 and 3\n", mat[0:2,[1,3]])

Matrix with row indices 0 and 1 and column indices 1 and 3
 [[39 27]
 [46 37]]


In [70]:
mat[0][1]=500

In [71]:
mat

array([[ 63, 500,  27,  44,  34],
       [ 41,  81,  74,  82,  42],
       [ 63,  97,  28,  97,  27]])

In [66]:
##Subseting
mat = np.array(ri(10,100,15)).reshape(3,5)
print("Matrix of random 2-digit numbers\n--------------------------------\n",mat)
mat>50

Matrix of random 2-digit numbers
--------------------------------
 [[63 93 27 44 34]
 [41 81 74 82 42]
 [63 97 28 97 27]]


array([[ True,  True, False, False, False],
       [False,  True,  True,  True, False],
       [ True,  True, False,  True, False]])

In [67]:
print ("Elements greater than 50\n", mat[mat>50])

Elements greater than 50
 [63 93 81 74 82 63 97 97]


In [72]:
##universal Function
mat1 = np.array(ri(1,10,9)).reshape(3,3)
mat2 = np.array(ri(1,10,9)).reshape(3,3)
print("\n1st Matrix of random single-digit numbers\n----------------------------------------\n",mat1)
print("\n2nd Matrix of random single-digit numbers\n----------------------------------------\n",mat2)



1st Matrix of random single-digit numbers
----------------------------------------
 [[1 1 2]
 [9 9 8]
 [1 3 2]]

2nd Matrix of random single-digit numbers
----------------------------------------
 [[5 9 5]
 [4 5 7]
 [1 6 8]]


In [74]:
mat1*mat2   ##element wise multiplication

array([[ 5,  9, 10],
       [36, 45, 56],
       [ 1, 18, 16]])

In [76]:
print("\nAddition\n------------------\n", mat1+mat2)
print("\nMultiplication\n------------------\n", mat1@mat2)   ##Real matrix multiplication



Addition
------------------
 [[ 6 10  7]
 [13 14 15]
 [ 2  9 10]]

Multiplication
------------------
 [[ 11  26  28]
 [ 89 174 172]
 [ 19  36  42]]


In [78]:
print("\nDivision\n------------------\n", mat1/0)

print("\nLineaer combination: 3*A - 2*B\n-----------------------------\n", 3*mat1-2*mat2)


Division
------------------
 [[inf inf inf]
 [inf inf inf]
 [inf inf inf]]

Lineaer combination: 3*A - 2*B
-----------------------------
 [[ -7 -15  -4]
 [ 19  17  10]
 [  1  -3 -10]]


C:\Users\GULAM ALI KHAN\Anaconda\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.


In [79]:
print("\nAddition of a scalar (100)\n-------------------------\n", 100+mat1)



Addition of a scalar (100)
-------------------------
 [[101 101 102]
 [109 109 108]
 [101 103 102]]


In [80]:
print("\nExponentiation, matrix cubed here\n----------------------------------------\n", mat1**3)
print("\nExponentiation, sq-root using pow function\n-------------------------------------------\n",pow(mat1,3))


Exponentiation, matrix cubed here
----------------------------------------
 [[  1   1   8]
 [729 729 512]
 [  1  27   8]]

Exponentiation, sq-root using pow function
-------------------------------------------
 [[  1   1   8]
 [729 729 512]
 [  1  27   8]]


In [82]:
##Broadcasting
start = np.zeros((4,4))
start= start+100   ##element wise broadcasting
start

array([[100., 100., 100., 100.],
       [100., 100., 100., 100.],
       [100., 100., 100., 100.],
       [100., 100., 100., 100.]])

In [83]:
# create a rank 1 ndarray with 4 values
add_rows = np.array([1, 0, 2,5])
print(add_rows)

[1 0 2 5]


In [84]:
y = start + add_rows  # add to each row of 'start' using broadcasting
print(y)              ##column wise broadcasting

[[101. 100. 102. 105.]
 [101. 100. 102. 105.]
 [101. 100. 102. 105.]
 [101. 100. 102. 105.]]


In [85]:
# create an ndarray which is 4 x 1 to broadcast across columns
add_cols = np.array([[0,1,2,3]])
add_cols = add_cols.T
print(add_cols)

[[0]
 [1]
 [2]
 [3]]


In [86]:
# add to each column of 'start' using broadcasting
y = start + add_cols    ##raw wise broadcasting
print(y)

[[100. 100. 100. 100.]
 [101. 101. 101. 101.]
 [102. 102. 102. 102.]
 [103. 103. 103. 103.]]


In [87]:
mat1 = np.array(ri(1,10,9)).reshape(3,3)
mat2 = np.array(ri(1,10,9)).reshape(3,3)
print("\n1st Matrix of random single-digit numbers\n\n",mat1)
print("\n2nd Matrix of random single-digit numbers\n------------\n",mat2)




1st Matrix of random single-digit numbers

 [[2 1 9]
 [3 8 8]
 [2 8 3]]

2nd Matrix of random single-digit numbers
------------
 [[5 2 3]
 [6 5 1]
 [5 5 6]]


In [88]:
##general mathematical 
print("\nSq-root of 1st matrix using np\n------------------\n", np.sqrt(mat1))



Sq-root of 1st matrix using np
------------------
 [[1.41421356 1.         3.        ]
 [1.73205081 2.82842712 2.82842712]
 [1.41421356 2.82842712 1.73205081]]


In [89]:
print("\nExponential power of 1st matrix using np\n",'-'*50,"\n", np.exp(mat1))



Exponential power of 1st matrix using np
 -------------------------------------------------- 
 [[7.38905610e+00 2.71828183e+00 8.10308393e+03]
 [2.00855369e+01 2.98095799e+03 2.98095799e+03]
 [7.38905610e+00 2.98095799e+03 2.00855369e+01]]


In [90]:
print("\n10-base logarithm on 1st matrix using np\n",'-'*50,"\n", np.log10(mat1))
print(mat1)
print(mat2)


10-base logarithm on 1st matrix using np
 -------------------------------------------------- 
 [[0.30103    0.         0.95424251]
 [0.47712125 0.90308999 0.90308999]
 [0.30103    0.90308999 0.47712125]]
[[2 1 9]
 [3 8 8]
 [2 8 3]]
[[5 2 3]
 [6 5 1]
 [5 5 6]]


In [91]:
print("\nModulo reminder using np\n",'-'*50,"\n", np.fmod(mat1,mat2))
mat1%mat2  ##Both gives same o/p


Modulo reminder using np
 -------------------------------------------------- 
 [[2 1 0]
 [3 3 0]
 [2 3 3]]


array([[2, 1, 0],
       [3, 3, 0],
       [2, 3, 3]], dtype=int32)